### ISSUE TITLE
Unable to create the sqlite db by exporting the data excel file

### ISSUE THREAD

**Issue by gkakkar** [MovalysMDK/mdk-cli-config#1]
Hello Team,
I was creating the Sample Android app using Movalys and unable to create the sqlitecreate_userdata file.This is document link which  i am referring is:
### https://www.movalys.org/docs/librariesprovider2/Movalys-MDK-Document/hands-on-mdk-android---support.pdf?sfvrsn=4

Below are the steps i followed and step two is not clear.(What is Tab<<Admin>> and where to click << Export>>)
1. Open myexpenses/hands-on/android/33 – Datas/MOV-MM-Referentiel_de_donnees-V1.11.xls
2. Tab « Admin », click on « Export »(**THIS STEP IS NOT CLEARED**)
3. A file named sqlitecreate_userdata is generated
4. Replace myexpenses/android/app/src/main/res/raw/sqlitecreate_userdata with this file
5. Build

Please refer page 11 of document for above steps.

**Comment by ghost** [comment]
Hello,

I will look into it and give you a feedback ASAP.

Simon

**Comment by ghost** [comment]
Hello again,

As a matter of fact, there seems to be a few problems with this paragraph of the document.
We are working on a solution.
In the meanwhile, you may use the attached file to add data to your generated application.
Just unzip it and replace the existing file in myexpenses/android/app/src/main/res/raw/sqlitecreate_userdata with this one, compile the project using the `mdk platform-compile android` command and install the generated apk on your device.

Simon

[sqlitecreate_userdata.zip](https://github.com/MovalysMDK/mdk-cli-config/files/209898/sqlitecreate_userdata.zip)

**Comment by gkakkar** [comment]
Thanks Simon.
Sqlite db works fine.
