### ISSUE TITLE
Apache Maven Installation failed: Download failed with status code : 404

### ISSUE THREAD

**Issue by madhusinghandroid** [MovalysMDK/mdk-cli-config#2]
Hi,

I am trying to set up using hands on android, by following "mdk tools-install android" its not able to download maven and is giving error Installation failed: Download failed with status code : 404.I tried to achieve it by manually downloading apache-maven 3.3.3 and extracting it to .mdk/tools/apache-maven 3.3.3,and set up the path but its not recognizing it.I have attached the error screenshot for reference.
![movalys_maven](https://cloud.githubusercontent.com/assets/20399221/16732480/1214127a-479b-11e6-816d-07460c246793.png)

**Comment by mlaffargue** [comment]
Hi @madhusinghandroid, the mirror we're using did remove the 3.3.3 version of maven to put the 3.3.9.
We did update our configuration file but you may have some cache problem.
Can you try using:
`mdk clear-cache` then retry using `mdk tools-install android`

Regards

**Comment by madhusinghandroid** [comment]
Hi @mlaffargue  Thanks for the assistance! I tried clearing cache and installing android tools but its trying to download maven from same mirror site as earlier.I have attached the screenshot for reference.
![movalysmavendownloaderror](https://cloud.githubusercontent.com/assets/20399221/16757314/b74594b6-4828-11e6-8464-6a6ad3f1210a.png)

**Comment by mlaffargue** [comment]
We did some tweaking on the client, can you try installing it again using `npm i -g mdk-cli`.

Thanks.

**Comment by madhusinghandroid** [comment]
Hi @mlaffargue 

Its working.

Thanks
