### ISSUE TITLE
 [Error]  Create project failed: applicationId must be lowercase Alphabet only an d must contain at least two dots.

### ISSUE THREAD

**Issue by madhusinghandroid** [MovalysMDK/mdk-cli-config#3]
Hi @mlaffargue ,
I was trying to create a new project but its giving me following error :
[Error]  Create project failed: application Id must be lowercase Alphabet only an
d must contain at least two dots.
Please refer to the screenshot attached.

Thanks
![movalys_createproject](https://cloud.githubusercontent.com/assets/20399221/16793425/8b95786a-48ee-11e6-9a32-75be99c6a153.png)

**Comment by mlaffargue** [comment]
Hi, the name of the project is taken from the last part of the package you give.
In your case that would be `mdk create com.steria.mdk.android.myfirstapp` for example and the application id will be `myfirstapp`.
This should be stated in the doc if you just  execute `mdk`

**Comment by madhusinghandroid** [comment]
Thanks @mlaffargue it worked.
